data:
  hdf5_path: /path/to/the/directory
  val_hdf5_path: /path/to/the/file.hdf5
  how2sign:
    path: /path/to/the/directory
  captions:
    path: /path/to/the/directory
    max_characters: 200
    max_seconds: 20
    min_seconds: 0.5
    langs: # null to include all languages
      - en
      - es
  videos:
    path: /path/to/the/directory
  keypoints:
    frame_freq: 2
    mediapipe_model_complexity: 1
    use_z: true
    main_pose_landmarks:
      include_face: true
      include_hands: true
      include_hips: false
  random_clips:
    chunk_seconds: 34 # "n=34" from the paper
    min_duration_seconds: 17 # "m=17" from the paper
  mt_pairs:
    - en-es
model:
  model_name: google/t5-v1_1-base
  lora: false
  save_path: /gscratch5/users/balkain001/TRAIN/byt5
generation:
  beam_size: 5
  max_length: 128
training:
  max_tokens: 800
  initial_data_proportions:
    mt: 0
    caption_clip: 1
    random_clip: 0
  data_proportions:
    mt: 0
    caption_clip: 0.5
    random_clip: 0.5
  target_effective_batch_size: 128
  finetune_target_effective_batch_size: 128
  initial_per_device_batch_sizes:
    train: 64
    eval: 128
  per_device_batch_sizes:
    train: 8
    eval: 128
  finetune_per_device_batch_sizes:
    train: 32
    eval: 128
  initial_max_steps: 100000
  max_steps: 100000
